//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemPayroll
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payslip
    {
        public int ID { get; set; }
        public System.DateTime Date_From { get; set; }
        public System.DateTime Date_To { get; set; }
        public decimal Hours_Worked { get; set; }
        public string Employee { get; set; }
        public Nullable<decimal> Overtime { get; set; }
    
        public virtual Employee Employee1 { get; set; }
    }
}
