//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemPayroll
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tax_Rate
    {
        public int ID { get; set; }
        public decimal Income_From { get; set; }
        public decimal Income_To { get; set; }
        public decimal Rate { get; set; }
    }
}
